# Generated by Django 4.2.2 on 2023-06-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytId', models.TextField(default='null', max_length=20)),
                ('url', models.CharField(default='null', max_length=200)),
                ('lang', models.CharField(default='null', max_length=30)),
                ('title', models.CharField(default='null', max_length=200)),
                ('description', models.TextField(default='null')),
                ('published_date', models.DateField(default='null')),
                ('transcript', models.TextField(default='null')),
                ('gptRaw', models.TextField(default='null')),
                ('gptSummary', models.TextField(default='null')),
                ('gptRec1', models.TextField(default='null')),
                ('gptRec2', models.TextField(default='null')),
            ],
        ),
    ]
