# Generated by Django 4.2.2 on 2023-06-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SumTube_Project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='gptRaw',
            new_name='STRaw',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='gptRec1',
            new_name='STRec1',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='gptRec2',
            new_name='STRec2',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='gptSummary',
            new_name='STSummary',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='transcript',
            new_name='STtranscript',
        ),
    ]
