# Generated by Django 4.2.2 on 2023-06-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SumTube_Project', '0003_video_yttranscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='STtranscript',
        ),
    ]
