# Generated by Django 4.2.2 on 2024-01-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SumTube_Project', '0005_video_sttranscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='STRaw',
            new_name='gptRaw',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='STRec1',
            new_name='gptRec1',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='STRec2',
            new_name='gptRec2',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='STSummary',
            new_name='gptSummary',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='STtranscript',
            new_name='transcript',
        ),
        migrations.RemoveField(
            model_name='video',
            name='YTtranscript',
        ),
    ]
